# Generated by Django 5.2.7 on 2025-11-22 00:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudflareZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("zone_id", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Cloudflare Zone",
                "verbose_name_plural": "Cloudflare Zones",
                "permissions": (
                    ("zone_pull_all", "Can pull all zones from Cloudflare"),
                    ("zone_pull_any", "Can pull any zone from Cloudflare (Including DNS records)"),
                    ("zone_pull_any_dns", "Can pull any zone DNS records from Cloudflare"),
                    ("zone_pull", "Can pull zone from Cloudflare (Including DNS records)"),
                    ("zone_pull_dns", "Can pull zone DNS records from Cloudflare"),
                ),
            },
        ),
        migrations.CreateModel(
            name="HistoricalCloudflareDNSRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("dns_id", models.CharField(blank=True, db_index=True, max_length=50)),
                ("name", models.CharField(max_length=30)),
                (
                    "dns_type",
                    models.CharField(
                        choices=[("A", "A"), ("AAAA", "AAAA"), ("CNAME", "CNAME")], max_length=10
                    ),
                ),
                ("content", models.CharField(max_length=30)),
                ("proxiable", models.BooleanField(default=False)),
                ("proxied", models.BooleanField(default=False)),
                ("ttl", models.IntegerField(blank=True, null=True)),
                ("auto_ttl", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cloudflare.cloudflarezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Cloudflare DNS Record",
                "verbose_name_plural": "historical Cloudflare DNS Records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCloudflareZone",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("zone_id", models.CharField(db_index=True, max_length=50)),
                ("status", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Cloudflare Zone",
                "verbose_name_plural": "historical Cloudflare Zones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CloudflareDNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dns_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "dns_type",
                    models.CharField(
                        choices=[("A", "A"), ("AAAA", "AAAA"), ("CNAME", "CNAME")], max_length=10
                    ),
                ),
                ("content", models.CharField(max_length=30)),
                ("proxiable", models.BooleanField(default=False)),
                ("proxied", models.BooleanField(default=False)),
                ("ttl", models.IntegerField(blank=True, null=True)),
                ("auto_ttl", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_records",
                        to="cloudflare.cloudflarezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cloudflare DNS Record",
                "verbose_name_plural": "Cloudflare DNS Records",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("dns_type__in", ["A", "AAAA", "CNAME"])),
                        name="cloudflare_dns_valid_type",
                        violation_error_message="DNS type must be one of: A, AAAA, CNAME",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ttl__isnull", True),
                            models.Q(("ttl__gte", 60), ("ttl__lte", 86400)),
                            _connector="OR",
                        ),
                        name="cloudflare_dns_ttl_range",
                        violation_error_message="TTL must be between 60 and 86400 seconds when set.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("proxiable", True), ("proxied", False), _connector="OR"
                        ),
                        name="cloudflare_dns_proxied_requires_proxiable",
                        violation_error_message="Proxied must be False when the record is not proxiable.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("auto_ttl", True), ("ttl__isnull", True)),
                            models.Q(("auto_ttl", False), ("ttl__isnull", False)),
                            _connector="OR",
                        ),
                        name="cloudflare_dns_auto_ttl_consistency",
                        violation_error_message="TTL must be null if auto ttl is enabled.",
                    ),
                ],
            },
        ),
    ]
