# Generated by Django 5.2.7 on 2025-11-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloudflare", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cloudflarednsrecord",
            options={
                "permissions": (
                    ("update", "Update DNS Record"),
                    ("delete", "Delete DNS Record"),
                    ("pull", "Pull DNS Record"),
                    ("push", "Push DNS Record"),
                ),
                "verbose_name": "Cloudflare DNS Record",
                "verbose_name_plural": "Cloudflare DNS Records",
            },
        ),
        migrations.AlterModelOptions(
            name="cloudflarezone",
            options={
                "permissions": (
                    ("pull_zone", "Pull Zone"),
                    ("pull_zone_dns", "Pull Zone DNS Records"),
                ),
                "verbose_name": "Cloudflare Zone",
                "verbose_name_plural": "Cloudflare Zones",
            },
        ),
    ]
