# Generated by Django 5.2.7 on 2025-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudflare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudflarednsrecord",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcloudflarednsrecord",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
