# Generated by Django 5.2.7 on 2025-11-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloudflare", "0002_alter_cloudflarednsrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cloudflarednsrecord",
            options={
                "permissions": (("pull", "Can pull DNS record"), ("push", "Can push DNS record")),
                "verbose_name": "Cloudflare DNS Record",
                "verbose_name_plural": "Cloudflare DNS Records",
            },
        ),
        migrations.AlterModelOptions(
            name="cloudflarezone",
            options={
                "permissions": (
                    ("pullall", "Can pull all zones from Cloudflare"),
                    ("pullany", "Can pull any zone from Cloudflare (Including DNS records)"),
                    ("pullanydns", "Can pull any zone DNS records from Cloudflare"),
                    ("pull", "Can pull zone from Cloudflare (Including DNS records)"),
                    ("pulldns", "Can pull zone DNS records from Cloudflare"),
                ),
                "verbose_name": "Cloudflare Zone",
                "verbose_name_plural": "Cloudflare Zones",
            },
        ),
    ]
