# Generated by Django 5.2.7 on 2025-11-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudflare", "0002_alter_cloudflarednsrecord_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudflarednsrecord",
            name="dns_type",
            field=models.CharField(
                choices=[("A", "A"), ("AAAA", "AAAA"), ("CNAME", "CNAME")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="historicalcloudflarednsrecord",
            name="dns_type",
            field=models.CharField(
                choices=[("A", "A"), ("AAAA", "AAAA"), ("CNAME", "CNAME")], max_length=10
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudflarednsrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("dns_type__in", ["A", "AAAA", "CNAME"])),
                name="cloudflare_dns_valid_type",
                violation_error_message="DNS type must be one of: A, AAAA, CNAME",
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudflarednsrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ttl__isnull", True),
                    models.Q(("ttl__gte", 60), ("ttl__lte", 86400)),
                    _connector="OR",
                ),
                name="cloudflare_dns_ttl_range",
                violation_error_message="TTL must be between 60 and 86400 seconds when set.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudflarednsrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("proxiable", True), ("proxied", False), _connector="OR"),
                name="cloudflare_dns_proxied_requires_proxiable",
                violation_error_message="Proxied must be False when the record is not proxiable.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudflarednsrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("auto_ttl", True), ("ttl__isnull", True)),
                    models.Q(("auto_ttl", False), ("ttl__isnull", False)),
                    _connector="OR",
                ),
                name="cloudflare_dns_auto_ttl_consistency",
                violation_error_message="TTL must be null if auto ttl is enabled.",
            ),
        ),
    ]
