name: hp

services:
  maintenance:
    container_name: maintenance
    restart: unless-stopped
    image: ghcr.io/evanlab02/hp2-caddy:0.7.13  # x-release-please-version
    command: "run --config /etc/caddy/maintenance/Caddyfile --adapter caddyfile"
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf/certs/:/certs
      - ./conf/custom/:/etc/caddy
      - maintenance-data:/data
    networks:
      - hp-network

volumes:
  maintenance-data:
    external: false

networks:
  hp-network:
    driver: bridge
