services:
  app_dev:
    container_name: app_dev
    restart: unless-stopped
    build:
      context: apps/homeportal
      dockerfile: Dockerfile
      target: app
    env_file:
      - .env
    volumes:
      - ./modules/servarr/gluetun/:/app/qbit/config
    networks:
      - hp-network

  admin_dev:
    container_name: admin_dev
    restart: unless-stopped
    build:
      context: apps/homeportal
      dockerfile: Dockerfile
      target: admin
    env_file:
      - .env
    volumes:
      - ./modules/servarr/gluetun/:/app/qbit/config
    networks:
      - hp-network

  queue_dev:
    container_name: queue_dev
    restart: unless-stopped
    build:
      context: apps/homeportal
      dockerfile: Dockerfile
      target: queue
    env_file:
      - .env
    volumes:
      - ./modules/servarr/gluetun/:/app/qbit/config
    networks:
      - hp-network
