name: hp

services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    image: ghcr.io/evanlab02/hp2-caddy:0.1.3  # x-release-please-version
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf/certs/:/certs
      - caddy-data:/data
    networks:
      - hp-network

  app:
    container_name: app
    restart: unless-stopped
    image: ghcr.io/evanlab02/hp2-app:0.1.3  # x-release-please-version
    env_file:
      - .env
    networks:
      - hp-network

  admin:
    container_name: admin
    restart: unless-stopped
    image: ghcr.io/evanlab02/hp2-admin:0.1.3  # x-release-please-version
    env_file:
      - .env
    networks:
      - hp-network

  valkey:
    image: valkey/valkey:8.1.4-alpine3.22
    container_name: valkey
    restart: unless-stopped
    volumes:
      - valkey-data:/data
    networks:
      - hp-network

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:17.6-alpine3.22
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - hp-network

volumes:
  caddy-data:
    external: false
  valkey-data:
    external: false
  postgres-data:
    external: false

networks:
  hp-network:
    driver: bridge
