"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from os import getenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = False
ROOT_URLCONF = "app.settings.core.urls"
SECRET_KEY = getenv("DJANGO_SECRET_KEY")
HOSTS: list[str] = [host for host in getenv("DJANGO_HOSTS", "").split(",") if host != ""]
WSGI_APPLICATION = "app.wsgi.application"
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
STATIC_URL = "static/"
STATIC_ROOT = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ALLOWED_HOSTS = ["localhost"]
if HOSTS:
    ALLOWED_HOSTS += HOSTS
    CSRF_TRUSTED_ORIGINS = HOSTS

THIRD_PARTY_APPS = ["import_export", "guardian", "simple_history", "constance"]

UNFOLD_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.constance",
]

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

APPS = ["api.apps.ApiConfig", "utils.apps.UtilsConfig"]

INSTALLED_APPS = UNFOLD_APPS + THIRD_PARTY_APPS + DJANGO_APPS + APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("DJANGO_DB_NAME"),
        "USER": getenv("DJANGO_DB_USER"),
        "PASSWORD": getenv("DJANGO_DB_PASSWORD"),
        "HOST": getenv("DJANGO_DB_HOST"),
        "PORT": getenv("DJANGO_DB_PORT", "5432"),
        "OPTIONS": {
            "pool": {
                "min_size": 1,
                "max_size": 4,
            },
        },
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"valkey://{getenv('DJANGO_CACHE_HOST')}:{getenv('DJANGO_CACHE_PORT', "6379")}",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = ["django.contrib.auth.hashers.Argon2PasswordHasher"]
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_CONFIG = {
    "TODO": ("TODO", "TODO"),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "*": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


UNFOLD = {
    "SITE_TITLE": "Home Portal",
    "SITE_HEADER": "Home Portal Administration",
    "SITE_URL": "/admin/",
    # "SITE_ICON": {
    #     "light": lambda: "static/icons/icon-light.svg",
    #     "dark": lambda: "static/icons/icon-dark.svg",
    # },
    # "SITE_LOGO": {
    #     "light": lambda: "static/logo/logo-light.svg",
    #     "dark": lambda: "static/logo/logo-dark.svg",
    # },
    "SITE_SYMBOL": "home",
    # "SITE_FAVICONS": [
    #     {
    #         "rel": "icon",
    #         "sizes": "32x32",
    #         "type": "image/png",
    #         "href": lambda: "static/favicon/favicon-32x32.png",
    #     },
    # ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    # Environment Indicator (helpful for dev/staging/prod)
    # "ENVIRONMENT": lambda: "local",
    # "ENVIRONMENT": lambda: ("Development", "warning"),  # ("label", "type")
    # where type can be: "info", "danger", "warning", "success"
    "BORDER_RADIUS": "8px",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Navigation",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": lambda request: "/admin/",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": lambda request: "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": lambda request: "/admin/auth/group/",
                    },
                ],
            },
            {
                "title": "Settings",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Configuration",
                        "icon": "settings",
                        "link": lambda request: "/admin/constance/config/",
                    },
                ],
            },
        ],
    },
    # "LOGIN": {
    #     "image": lambda: "static/images/login-bg.jpg",
    # },
    # "STYLES": [
    #     lambda request: "static/css/custom.css",
    # ],
    # "SCRIPTS": [
    #     lambda request: "static/js/custom.js",
    # ],
}
