services:
  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4:9.8.0
    env_file:
      - .env
    environment:
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    networks:
      - hp-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - flame.type=application
      - flame.name=Postgres Admin
      - flame.url=https://pgadmin.labuschagne.xyz
      - flame.icon=database-cog

volumes:
  pgadmin-data:
    external: false