services:
  gluetun:
    container_name: gluetun
    restart: unless-stopped
    image: qmcgaw/gluetun:v3.40.0
    ports:
      - "6500:6500"
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
    volumes:
      - gluetun-data:/gluetun
      - ./gluetun/:/tmp/gluetun/
    networks:
      - hp-network

  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    image: lscr.io/linuxserver/qbittorrent:5.1.2
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    network_mode: "service:gluetun"
    volumes:
      - qbittorrent-config:/config
      - SETTOLOCATION:/downloads
    labels:
      - flame.type=application
      - flame.name=qBittorrent
      - flame.url=https://torrent.labuschagne.xyz
      - flame.icon=download

  rdtclient:
    image: rogerfar/rdtclient:2.0.119
    container_name: rdtclient
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - rdt-config:/data/db
      - SETTOLOCATION:/data/downloads
    labels:
      - flame.type=application
      - flame.name=Media Downloads
      - flame.url=https://downloads.labuschagne.xyz
      - flame.icon=download
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  tubesync:
    image: ghcr.io/meeb/tubesync:v0.15.11
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - DATABASE_CONNECTION=postgresql://${TUBESYNC_USER}:${TUBESYNC_PW}@${TUBESYNC_HOST}/${TUBESYNC_DB}
    volumes:
      - tubesync-config:/config
      - SETTOLOCATION:/data/downloads

  byparr:
    container_name: byparr
    restart: unless-stopped
    image: ghcr.io/thephaseless/byparr:2.0.1
    init: true
    ports:
      - "8191:8191"

  seerr:
    container_name: seerr
    restart: unless-stopped
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3
    init: true
    environment:
      - LOG_LEVEL=debug
      - TZ=Africa/Johannesburg
      - PORT=5055
    ports:
      - 9997:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    volumes:
      - seerr-config:/app/config
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=Seerr
      - flame.url=https://seerr.labuschagne.xyz
      - flame.icon=movie-open

  prowlarr:
    container_name: prowlarr
    restart: unless-stopped
    image: lscr.io/linuxserver/prowlarr:2.1.5
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr-config:/config
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=Prowlarr
      - flame.url=https://prowlarr.labuschagne.xyz
      - flame.icon=download
  
  radarr:
    container_name: radarr
    restart: unless-stopped
    image: lscr.io/linuxserver/radarr:5.28.0
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr-config:/config
      - SETTOLOCATION:/movies/int1
      - SETTOLOCATION:/movies/ext1
      - SETTOLOCATION:/downloads
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=Radarr
      - flame.url=https://radarr.labuschagne.xyz
      - flame.icon=movie-open

  sonarr:
    container_name: sonarr
    restart: unless-stopped
    image: lscr.io/linuxserver/sonarr:4.0.15
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr-config:/config
      - SETTOLOCATION:/tv/int1
      - SETTOLOCATION:/tv/ext1
      - SETTOLOCATION:/downloads
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=sonarr
      - flame.url=https://sonarr.labuschagne.xyz
      - flame.icon=movie-open

volumes:
  gluetun-data:
    external: false
  qbittorrent-config:
    external: false
  rdt-config:
    external: false
  seerr-config:
    external: false
  prowlarr-config:
    external: false
  radarr-config:
    external: false
  sonarr-config:
    external: false
  tubesync-config:
    external: false
