name: build

permissions: write-all

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Images
        run: |
          docker build -f Dockerfile -t hp2-caddy:latest .
          docker build -f Dockerfile.dev -t hp2-caddy:latest .
          docker build -f documentation/Dockerfile.dev -t hp2-documentation-dev:latest documentation/
