name: lint

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/homeportal
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "apps/homeportal/requirements.txt"
      - name: Install dependencies
        run: |
          uv pip install -r requirements.dev.txt
      - name: Lint
        run: |
          black --check .
          isort . --check-only --profile black
          flake8 . --max-line-length=100
