name: release

permissions: write-all

on:
  push:
    branches:
      - trunk

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  images:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build App Image
        run: |
          docker build -f Dockerfile -t hp2-caddy:latest .
          docker build -f apps/homeportal/docker/admin/Dockerfile -t hp2-admin:latest apps/homeportal/
          docker build -f apps/homeportal/docker/app/Dockerfile -t hp2-app:latest apps/homeportal/
          docker build -f apps/homeportal/docker/queue/Dockerfile -t hp2-queue:latest apps/homeportal/
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Create Tags
        run: |
          docker tag hp2-caddy:latest ghcr.io/evanlab02/hp2-caddy:latest
          docker tag hp2-caddy:latest ghcr.io/evanlab02/hp2-caddy:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker tag hp2-admin:latest ghcr.io/evanlab02/hp2-admin:latest
          docker tag hp2-admin:latest ghcr.io/evanlab02/hp2-admin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker tag hp2-app:latest ghcr.io/evanlab02/hp2-app:latest
          docker tag hp2-app:latest ghcr.io/evanlab02/hp2-app:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker tag hp2-queue:latest ghcr.io/evanlab02/hp2-queue:latest
          docker tag hp2-queue:latest ghcr.io/evanlab02/hp2-queue:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
      - name: Push Tags
        run: |
          docker push ghcr.io/evanlab02/hp2-caddy:latest
          docker push ghcr.io/evanlab02/hp2-caddy:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker push ghcr.io/evanlab02/hp2-admin:latest
          docker push ghcr.io/evanlab02/hp2-admin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker push ghcr.io/evanlab02/hp2-app:latest
          docker push ghcr.io/evanlab02/hp2-app:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker push ghcr.io/evanlab02/hp2-queue:latest
          docker push ghcr.io/evanlab02/hp2-queue:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}

  docs:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    defaults:
      run:
        working-directory: documentation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "documentation/requirements.txt"
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Sync Changes
        run: |
          git fetch
      - name: Deploy Documentation
        run: |
          uv run mike deploy --push --update-aliases ${{ needs.release-please.outputs.tag_name }} latest
          uv run mike set-default --push latest
