name: release

permissions: write-all

on:
  push:
    branches:
      - trunk

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  images:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push hp2-caddy
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/evanlab02/hp2-caddy:latest
            ghcr.io/evanlab02/hp2-caddy:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          cache-from: type=gha,scope=caddy
          cache-to: type=gha,scope=caddy,mode=max
      - name: Build and push hp2-admin
        uses: docker/build-push-action@v6
        with:
          context: ./apps/homeportal
          file: ./apps/homeportal/Dockerfile
          target: admin
          push: true
          tags: |
            ghcr.io/evanlab02/hp2-admin:latest
            ghcr.io/evanlab02/hp2-admin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          cache-from: type=gha,scope=homeportal
          cache-to: type=gha,scope=homeportal,mode=max
      - name: Build and push hp2-app
        uses: docker/build-push-action@v6
        with:
          context: ./apps/homeportal
          file: ./apps/homeportal/Dockerfile
          target: app
          push: true
          tags: |
            ghcr.io/evanlab02/hp2-app:latest
            ghcr.io/evanlab02/hp2-app:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          cache-from: type=gha,scope=homeportal
          cache-to: type=gha,scope=homeportal,mode=max
      - name: Build and push hp2-queue
        uses: docker/build-push-action@v6
        with:
          context: ./apps/homeportal
          file: ./apps/homeportal/Dockerfile
          target: queue
          push: true
          tags: |
            ghcr.io/evanlab02/hp2-queue:latest
            ghcr.io/evanlab02/hp2-queue:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          cache-from: type=gha,scope=homeportal
          cache-to: type=gha,scope=homeportal,mode=max

  docs:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    defaults:
      run:
        working-directory: documentation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "documentation/requirements.txt"
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Sync Changes
        run: |
          git fetch
      - name: Deploy Documentation
        run: |
          uv run mike deploy --push --update-aliases ${{ needs.release-please.outputs.tag_name }} latest
          uv run mike set-default --push latest
